### ISSUE TITLE
Is there any planning for python2 support?

### ISSUE THREAD

**Issue by Stonesjtu** [src-d/kmcuda#23]
And what's the point to restrict usage only on python3. I would like to write a version both compatible for python2 and python3 if possible.

**Comment by vmarkovtsev** [comment]
Hi!

2.7 will retire in 2020: https://pythonclock.org/
Django has abandoned 2: https://news.ycombinator.com/item?id=13433927
Scientific stack (numpy, etc.) are dropping 2 no later than 2020 http://www.python3statement.org/

Thus I see no point in supporting Py2. Unfortunately, it adds much mess into the code and especially into the native modules. Since this package is young, the decision was to exclude 2.7 from the very beginning.

Feel free to fork this project and adapt to your needs: the license permits it. I can place a link to it in the README.
